name: create-repo
on:
  workflow_dispatch:
    inputs:
      prefix:
        description: "set repo prefix"
        required: true
        default: "service"
        type: choice
        options:
          - example
          - service
      name:
        description: "set repo name"
        required: true
        default: "github-actions"
        type: string

jobs:
  create-repo-automation:
    runs-on: ubuntu-latest
    steps:
      - name: gh auth login
        run: |
          echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | gh auth login --with-token
      - name: create-repo
        id: create-repo
        run: |
          gh repo create hyungwon-action/${{ inputs.prefix }}-${{ inputs.name }} --public --add-readme
      - name: slack
        if: always()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload-file-path: "./payload-slack-content.json"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
